services:
  dev:
    image: golang:1.22.5-bookworm
    command: tail -f /dev/null
    environment:
      - DB_USER=dev
      - DB_PASSWORD=dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dforget
    ports:
      - 8080:8080
    volumes:
      - ./:/app
  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dforget
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
